FROM percona/percona-distribution-postgresql:18.1

# Install required packages using dnf
# We use 'dnf clean all' to keep the image slim
USER root
RUN dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-aarch64/pgdg-redhat-repo-latest.noarch.rpm \
  && dnf -qy module disable postgresql \
  && dnf install -y \
  python3-pip \
  python3-devel \
  wget \
  jq \
  git \
  make \
  percona-pgbouncer \
  percona-pgbackrest \
  pg_partman_18 \
  lz4 \
  zstd \
  net-tools

# Install Patroni
USER postgres
RUN pip3 install patroni[etcd3]

# clean up devel
USER root
RUN dnf remove -y \
  python3-devel \
  wget \
  git \
  make \
  && dnf clean all \
  && rm -rf /var/cache/dnf

# Create necessary directories
RUN mkdir -p /etc/patroni /data/db /data/pg_tde_keys && \
  mkdir -p /etc/postgresql/secrets && touch /etc/postgresql/secrets/vault_token.txt && \
  mkdir -p /etc/pgbouncer && \
  chown -R postgres:postgres /etc/patroni /data /etc/postgresql /etc/pgbouncer && \
  chmod 700 /data/db /data/pg_tde_keys && \
  chmod 600 /etc/postgresql/secrets/vault_token.txt

# Copy entrypoint and helper scripts
COPY entrypoint-postgres.sh /entrypoint.sh
COPY patroni-tde-basebackup.sh /usr/local/bin/patroni-tde-basebackup.sh
RUN chmod +x /entrypoint.sh /usr/local/bin/patroni-tde-basebackup.sh

# Expose PostgreSQL, Patroni, and PgBouncer ports
USER postgres
EXPOSE 5432 6432 8008

ENTRYPOINT ["/entrypoint.sh"]
CMD ["patroni", "/etc/patroni/patroni.yml"]