[global]
# S3 / MinIO repository
repo1-type=s3
repo1-s3-bucket=postgres-archive
repo1-s3-endpoint=https://minio:9000
repo1-s3-uri-style=path
repo1-s3-region=us-east-1
repo1-s3-key=pgbackrest
repo1-s3-key-secret=test-deni-123
repo1-storage-verify-tls=n
repo1-storage-ca-file=/etc/postgres/certs/ca.crt
repo1-path=/postgres-archive

# Logging
log-level-console=info
log-level-file=info

# Compression
compress-type=lz4

[postgres-patroni-tde]
pg1-path=/data/db
